appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: UHuDueBzMyleX9+AvDV2MVNS27XEZmxHqw2+zJEF1PQlv/N1bbaoAsWC5eHz0p5J7+yLWTIpZKHAy6o0PWygZDozTr3OZkwBQON6JcqwXkxZWrjS8Z49aAAfeavfZ18OFgTLhYJe3/k8f1K0iwHkFR1ARf2wxeVEvhwsXQNaSx/oZZF7nFKG0fdqE1IHFHvXN38JkqQVF/MbfIy418OtbQydI1xNaukGROvwxzShf8qgpi2wZ9I/6ceym3IGa0h0nRy10RyvQiWFGUuvK2PMrtbMlFKP1MatKKf64ga3wIAP/HFUbc3vXafcvYBZjmRJF/Gw56R53behPTetPewTWcWDPCOiIB9lV/zbXmcVcFS28en0txW+zBy27qCP621RggexjSh6O58F2OsuNVQvYSYW0zwn9MdZPAqFtxSWSKsXqOo4ySjFmht6k1iDcmMcey0lv0CGqaz1W37+YnsMNm2VEyYT5B1x9CxYSiVEmN/LgPWWVX6XGA1X1bUZ/VBsboGoK608lor2fP4xxuMLmrg+Xb5EQfnvYSnHP30tOdFjV35tXm3Iyxo7tJaFCKEaZseyITIbEEKvaRIIB6cSzq63krM+rrWfW/9R3nFwJbGDVYOrwG4McDmiFe62ZNiS2JcZySwrS5gz1h5s5b5Mmz6lPR3XNljC0FBiG8m1A08=}
provider:
  win: azure
bot:
  automerge: true
